# Generated by Django 5.0.7 on 2024-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Depósito'), (2, 'Saque'), (3, 'Juros'), (4, 'Transferência')]),
        ),
    ]
